//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaInnovation
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Infraccion
    {
        public int Id { get; set; }
        public string Identificador { get; set; }
        public DateTime FechaYHora { get; set; }
        public int ConductorId { get; set; }
        public int VehiculoId { get; set; }
    
        [JsonIgnore]
        public virtual Conductor Conductor { get; set; }

        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }

        [JsonIgnore]
        public virtual TipoInfraccion TipoInfraccion { get; set; }
    }
}
